### ISSUE TITLE
ImportError: cannot import name 'Roboto' from 'fonts.ttf' (/workspace/venv/lib/python3.10/site-packages/fonts/ttf/__init__.py)

### ISSUE THREAD

**Issue by FurkanGozukara** [AlUlkesh/sd_grid_add_image_number#10]
I am trying the extension on runpod which is ubuntu 22
not working

here error

```
Restarting UI...
Closing server running on port: 3000
2023-07-07 14:07:31,785 - ControlNet - INFO - ControlNet v1.1.224
Error loading script: sd_grid_add_image_number.py
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/stable-diffusion-webui/extensions/sd_grid_add_image_number/scripts/sd_grid_add_image_number.py", line 5, in <module>
    from fonts.ttf import Roboto
ImportError: cannot import name 'Roboto' from 'fonts.ttf' (/workspace/venv/lib/python3.10/site-packages/fonts/ttf/__init__.py)
```

**Comment by AlUlkesh** [comment]
Are you sure you have the current version of the extension?

Can you check if the file
`/workspace/stable-diffusion-webui/extensions/sd_grid_add_image_number/install.py`

looks like this:

```
import launch

if not launch.is_installed("font_roboto"):
    launch.run_pip("install font-roboto", "font-roboto requirement for grid_add_image_number")

if not launch.is_installed("fonts"):
    launch.run_pip("install fonts", "fonts requirement for grid_add_image_number")

```
?

**Comment by le-khang** [comment]
Hi Dr. Furkan, I didn't know that I would meet you here. I used the Ashleyk Runpod template and the extension doesn't work for me as well. It stopped working approximately three days ago and the grid images don't show any number. This is a very useful extension please check it AlUlkesh. Thank you very much.

**Comment by FurkanGozukara** [comment]
> Are you sure you have the current version of the extension?
> 
> Can you check if the file `/workspace/stable-diffusion-webui/extensions/sd_grid_add_image_number/install.py`
> 
> looks like this:
> 
> ```
> import launch
> 
> if not launch.is_installed("font_roboto"):
>     launch.run_pip("install font-roboto", "font-roboto requirement for grid_add_image_number")
> 
> if not launch.is_installed("fonts"):
>     launch.run_pip("install fonts", "fonts requirement for grid_add_image_number")
> ```
> 
> ?

i just installed latest version right now
commit hash

10a253b5ef261f3e39ea84486cab2ad743e61d41

```
*** Error loading script: sd_grid_add_image_number.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/sd_grid_add_image_number/scripts/sd_grid_add_image_number.py", line 5, in <module>
        from fonts.ttf import Roboto
    ModuleNotFoundError: No module named 'fonts'
```

the file you asked for

install py is as below

```
import launch

if not launch.is_installed("font_roboto"):
    launch.run_pip("install font-roboto", "font-roboto requirement for grid_add_image_number")

if not launch.is_installed("fonts"):
    launch.run_pip("install fonts", "fonts requirement for grid_add_image_number")
```

@le-khang

**Comment by AlUlkesh** [comment]
I wonder if you have this option in your `webui-user.sh`: `--skip-install` ? If so, please remove it and try again.

If not, you can try installing the packages manually, by doing this from the a1111 directory:

```
source venv/bin/activate
pip install font-roboto
pip install fonts

```
and then restart a1111.

**Comment by le-khang** [comment]
> I wonder if you have this option in your `webui-user.sh`: `--skip-install` ? If so, please remove it and try again.
> 
> If not, you can try installing the packages manually, by doing this from the a1111 directory:
> 
> ```
> source venv/bin/activate
> pip install font-roboto
> pip install fonts
> ```
> 
> and then restart a1111.

Yeah this is the solution for me. I used Runpod's pre-made template but my ADetailer extension didn't work. When I removed the "--skip-install" it started working again and I notice that sd_grid_add_image_number is working too.

**Comment by AlUlkesh** [comment]
Font-Install is no longer necessary.
