### ISSUE TITLE
Problem after WebUI v1.6.0 when using refiner

### ISSUE THREAD

**Issue by SLAPaper** [AlUlkesh/sd_grid_add_image_number#12]
using refiner will overwrite the checkpoint name in grid with refiner model, rather than the base model, which actually determine the overall image content.
or maybe it's better to seperate the base model and refiner model in grid

**Comment by AlUlkesh** [comment]
I have an idea on how to make the whole process of getting the xyz values more straightforward.

In your case, you'd get the base model if you chose checkpoint name in xyz, and the refiner model if you chose refiner in xyz.

Stay tuned...

**Comment by AlUlkesh** [comment]
I just finished the rework. Can you check if it works for you?

**Comment by SLAPaper** [comment]
> I just finished the rework. Can you check if it works for you?

@AlUlkesh It works just fine, thanks!
