### ISSUE TITLE
No numbers show up

### ISSUE THREAD

**Issue by 4DeepThought2** [AlUlkesh/sd_grid_add_image_number#2]
I am not able to get this to work.  No numbers show up, despite it being checked in options.

**Comment by AlUlkesh** [comment]
These conditions need to be fulfilled:
`if opts.sd_grid_add_image_number and opts.save_images_add_number and opts.samples_save:`

So:
1.
![image](https://user-images.githubusercontent.com/99896447/213796358-b1190018-99e1-40a8-871d-dded2a9a2b44.png)

2.
![image](https://user-images.githubusercontent.com/99896447/213796572-ff5d1138-4ea9-497f-98f0-9f00f0e6d9a2.png)

3.
![image](https://user-images.githubusercontent.com/99896447/213796755-5b327a6b-7533-4854-bdb9-7dcb712d322a.png)

Are these all set for you?

**Comment by 4DeepThought2** [comment]
Aha.  No, I do not set always save all generated images.  I'll just make a quick commit change in my local repo to review that check.  Thanks.
