### ISSUE TITLE
Feature request: Adding selected x/y/z values to grid image

### ISSUE THREAD

**Issue by Woisek** [AlUlkesh/sd_grid_add_image_number#3]
First, thanks for this helpful extension. During the use of it, I found out, that it would even more convenient, if we could have the selected x/y values also in the image.
I very often use the x/y for embedding comparisations. So I then mostly use CFG on x and the embedding value on y. Allthough those are labeld as legend, when scanning in fullscreen the single files (on a i.e. 4690 x 26204 pixel sized grid), those legend is not visible anmore.
Therefore it would be fantastic to have a checkbox that enables us to have those values also printed on the images of the grid.
I may suggest displaying x in the upper right, y in the lower left and the number in the lower right corner. Or maybe you make this even customizable. ;)

Again, thanks for this great work!

**Comment by AlUlkesh** [comment]
Ohhh... interesting idea. I also have run into that a lot. I'll look into it.

**Comment by Woisek** [comment]
Thanks! Can't wait for it. ;)

**Comment by AlUlkesh** [comment]
Quick question: With "the embedding value" you mean the name of the embedding?

**Comment by Woisek** [comment]
With "embedding value" I meant the name of the .pt file, like i.e. alberto-montt.pt, durer-style.pt or any-other-style-5000.pt. But basicly, just anything what is chosen as type for this axis.

Example:
I create a prompt with a "variable" in it. I. e. Bob-Ross-NUMBER

Script: X/Y/Z plot
X type: CFG scale
Y type: Prompt S/R

X values: 2,3,4,5,6,7,8,9,10
Y values: NUMBER,200,800,2000,8000


Output result on the images of the grid (second row, first row is NUMBER) would then possible be:

Upper right corner (x type value): CFG Scale: 2
Lower left corner (y type value); 200
Lower right corner (numbering): 0000
____
Upper right corner (x type value): CFG Scale: 3
Lower left corner (y type value); 200
Lower right corner (numbering): 0001
____
.
.
.
Third row would be:
Upper right corner (x type value): CFG Scale: 2
Lower left corner (y type value); 800
Lower right corner (numbering): 0000
____
Upper right corner (x type value): CFG Scale: 3
Lower left corner (y type value); 800
Lower right corner (numbering): 0001
____
.
.
.
You get the idea. :)
I hope this explains it for you. Thanks!

Edit: Or simply said: That, whats printed as legend on the axis should be in the respective corners of the images. :)

**Comment by AlUlkesh** [comment]
I've tried everything I could come up with to access the x/y/z values, but to no avail. I've now asked on the webui side.

**Comment by Woisek** [comment]
Oh, what a pity ... :(
I hope you can manage it anyway somehow. Good luck! :)

**Comment by AlUlkesh** [comment]
@Woisek 
My PR to expose the xyz values has finally made it into webui. So now I was able to get back to this. Here's the first version.
https://github.com/AlUlkesh/sd_grid_add_image_number#xyz-script-info

**Comment by Woisek** [comment]
Wow, you are THA MAN!! Awesome news! :D
Will update as soon as possible. Many thanks!!

**Comment by Woisek** [comment]
Allrighty ... this works perfect! Again, thanks for this nice addon! 👍

**Comment by Woisek** [comment]
Sorry to kinda re-open this again, but after some generations, I noticed, that the layout of the overlays are not quite optimal (IMHO).
May I request a re-position of them?
I would like the number on the top left, the x value on the top right and y value on the bottom left corner.
OR, and that would probably much better, an setting to configure the position ourselfes.

Would this be doable, please? :)

Edit:
I also noticed some rounding issues (or that kind). When I create a grid with denoise values from 0 to 1 in 0.1 steps, it does some weird, floating numbers on 0.3, 0.6 and 0.7. Image attached. I don't know if your script has anything to do with it (probably not), but maybe you can fix this with a decimal place limit or so, too. :)

![xyz_grid-0000-S=999853024-St=20-Sa=Euler a-Cfg=7](https://user-images.githubusercontent.com/122026301/223678660-dda8efa9-e06a-4fb7-b3d7-acb23372442a.jpg)

Thanks again!
