### ISSUE TITLE
fonts and font-roboto are not installed

### ISSUE THREAD

**Issue by jebarpg** [AlUlkesh/sd_grid_add_image_number#6]
Got an error from this extension stating these two modules were not installed.
I had to manually pip install these two modules in my venv.

**Comment by AlUlkesh** [comment]
Interesting. Those used to be installed by webui's requirements file. But apparently they have been removed there. I'll add them in here, thanks.

**Comment by AlUlkesh** [comment]
Should be fixed now.

**Comment by jebarpg** [comment]
awesome thanks :D
